### PR TITLE
Added router to demo app

### PR DESCRIPTION
**Pull request by jpdonaghy**

### CODE REVIEW

**Comment by thelgevold** [comment]
Looks good. 
In one of the next betas RouteConfig will be renamed to Routes, but that is a simple fix.

**Comment by jpdonaghy** [comment]
I want to move the entire demo to it's own folder are the root of src and get it out of components.

**Comment by jpdonaghy** [comment]
Merging this as it is, will move demo later.

**Comment by thelgevold** [comment]
Ok, sounds good

**Pull request merged**
