### PR TITLE
started validation

### PR DESCRIPTION
**Pull request by thelgevold**
This is just the start of validation, but I also fixed a bug/simplified our RX request

### CODE REVIEW

**Comment by thelgevold** [comment]
Yeah, I know. I want the parser to return the correct buckets eventually. One that needs a request and one that doesn't. We can figure out the names.

**Comment by thelgevold** [comment]
I am adding the rest of the built in validators now

**Comment by thelgevold** [comment]
Pushed the rest of the validators. Have to look into maxLength since it's default behavior seems to be to require the input to be exactly === maxLength. This seems like a bug to me

**Comment by thelgevold** [comment]
I logged issues, so I think we can merge this PR as is.

**Comment by jpdonaghy** [comment]
LGTM

**Pull request merged**
